# Generated by Django 2.1.7 on 2019-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='screenplay'),
        ),
    ]
