# Generated by Django 2.1.7 on 2019-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20190328_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logline',
            field=models.TextField(max_length=300),
        ),
    ]
