# Generated by Django 2.1.7 on 2019-03-28 12:48

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_auto_20190328_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=pyuploadcare.dj.models.FileField(),
        ),
    ]
