# Generated by Django 2.1.7 on 2019-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_auto_20190328_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='screenplay'),
        ),
    ]
