# Generated by Django 2.1.7 on 2019-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
