# Generated by Django 2.1.7 on 2019-03-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_auto_20190328_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
    ]
